# Generated by Django 2.2.2 on 2019-06-19 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True, verbose_name='phone number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('destination_address', models.TextField(blank=True, null=True, verbose_name='destination address')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pics', verbose_name='profile picture')),
                ('orders', models.ManyToManyField(related_name='ordered_by', to='orders.Order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
